CREATE TABLE "effect_mq_jobs" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"queue" text NOT NULL,
	"state" text NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL,
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"payload" jsonb,
	"metadata" jsonb DEFAULT '{}' NOT NULL,
	"attempts_max" integer NOT NULL,
	"attempts_made" integer DEFAULT 0 NOT NULL,
	"stalled_count" integer DEFAULT 0 NOT NULL,
	"backoff" jsonb,
	"keep" jsonb,
	"timeout_ms" bigint,
	"cancel_requested" boolean DEFAULT false NOT NULL,
	"dedupe_key" text,
	"trace" jsonb,
	"parent" jsonb,
	"flow_fail_fast" boolean,
	"flow_pending" integer,
	"flow_completed" integer,
	"flow_failed" integer,
	"flow_cancelled" integer,
	"run_at" timestamp with time zone NOT NULL,
	"enqueued_at" timestamp with time zone NOT NULL,
	"processed_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"exit" jsonb,
	"failed_reason" text,
	"lock_token" text,
	"lock_expires_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "effect_mq_job_attempts" (
	"job_id" text NOT NULL,
	"attempt" integer NOT NULL,
	"outcome" text NOT NULL,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone NOT NULL,
	"exit" jsonb,
	CONSTRAINT "effect_mq_job_attempts_job_id_attempt_pk" PRIMARY KEY("job_id","attempt")
);
--> statement-breakpoint
CREATE TABLE "effect_mq_schedules" (
	"key" text PRIMARY KEY NOT NULL,
	"job_name" text NOT NULL,
	"queue" text NOT NULL,
	"cron" text,
	"tz" text,
	"every_ms" bigint,
	"payload" jsonb,
	"metadata" jsonb DEFAULT '{}' NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL,
	"attempts_max" integer NOT NULL,
	"backoff" jsonb,
	"keep" jsonb,
	"timeout_ms" bigint,
	"group_name" text,
	"next_run_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "effect_mq_queue_control" (
	"queue" text PRIMARY KEY NOT NULL,
	"paused" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "effect_mq_dedupe" (
	"name" text NOT NULL,
	"key" text NOT NULL,
	"job_id" text NOT NULL,
	"window_expires_at" timestamp with time zone,
	CONSTRAINT "effect_mq_dedupe_name_key_pk" PRIMARY KEY("name","key")
);
--> statement-breakpoint
CREATE TABLE "effect_mq_flow_children" (
	"flow_id" text NOT NULL,
	"child_key" text NOT NULL,
	"name" text NOT NULL,
	"store_key" text NOT NULL,
	"spec" jsonb NOT NULL,
	"status" text NOT NULL,
	"exit" jsonb,
	"failed_reason" text,
	"cascaded" boolean NOT NULL,
	"pending_since" timestamp with time zone NOT NULL,
	CONSTRAINT "effect_mq_flow_children_flow_id_child_key_pk" PRIMARY KEY("flow_id","child_key")
);
--> statement-breakpoint
CREATE TABLE "effect_mq_flow_outbox" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"flow_name" text NOT NULL,
	"parent_store_key" text NOT NULL,
	"report" jsonb NOT NULL
);
--> statement-breakpoint
ALTER TABLE "effect_mq_job_attempts" ADD CONSTRAINT "effect_mq_job_attempts_job_id_effect_mq_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."effect_mq_jobs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_ready_idx" ON "effect_mq_jobs" USING btree ("queue","priority" DESC,"seq" ASC) WHERE "state" = 'waiting';--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_delayed_idx" ON "effect_mq_jobs" USING btree ("queue","run_at") WHERE "state" = 'delayed';--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_active_idx" ON "effect_mq_jobs" USING btree ("lock_expires_at") WHERE "state" = 'active';--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_history_idx" ON "effect_mq_jobs" USING btree ("name","state","finished_at");--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_listing_idx" ON "effect_mq_jobs" USING btree ("enqueued_at" DESC,"id" DESC);--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_metadata_idx" ON "effect_mq_jobs" USING gin ("metadata" jsonb_path_ops);--> statement-breakpoint
CREATE INDEX "effect_mq_schedules_due_idx" ON "effect_mq_schedules" USING btree ("next_run_at");--> statement-breakpoint
CREATE INDEX "effect_mq_flow_children_pending_idx" ON "effect_mq_flow_children" USING btree ("pending_since") WHERE "status" = 'pending';--> statement-breakpoint
CREATE INDEX "effect_mq_flow_children_cascade_idx" ON "effect_mq_flow_children" USING btree ("flow_id") WHERE "status" = 'cancelled' AND NOT "cascaded";
