packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  sharp: true
catalog:
  zod: ^4.5.4
  typescript: ^6.0.3
  varlock: 1.18.0
  "@orpc/server": ^1.15.0
  "@orpc/client": ^1.15.0
  "@orpc/openapi": ^1.15.0
  "@orpc/zod": ^1.15.0
  better-auth: 1.7.3
