services:
    sidecar:
        build:
            context: .
            dockerfile: Dockerfile
        image: ghcr.io/irazvan2745/sidecar:latest
        volumes:
            # Bind-mount host's Uncloud socket directory.
            - /run/uncloud:/run/uncloud:ro
        # Set UNCLOUD_SOCKET_GID when the socket is not owned by root:root.
        restart: unless-stopped
        deploy:
            mode: global
