name: Feature request
description: Suggest an improvement to Stoat
title: "feat: "
labels:
    - enhancement
body:
    - type: textarea
      id: problem
      attributes:
          label: What problem would this solve?
          description: Explain the use case and who benefits from it.
      validations:
          required: true
    - type: textarea
      id: proposal
      attributes:
          label: What would you like to see?
          description: Describe the proposed behavior or API.
      validations:
          required: true
    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives considered
