CREATE TABLE "data_source" (
	"id" text PRIMARY KEY,
	"organization_id" text NOT NULL,
	"git_url" text,
	"uncloud_url" text NOT NULL,
	"uncloud_token" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "deployment_logs" (
	"id" bigserial PRIMARY KEY,
	"deployment_id" text NOT NULL,
	"stream" text NOT NULL,
	"message" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "deployments" (
	"id" text PRIMARY KEY,
	"service_id" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"queued_at" timestamp with time zone,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"outcome" text,
	"job_id" text,
	"settings" jsonb DEFAULT '{}' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "effect_mq_dedupe" (
	"name" text,
	"key" text,
	"job_id" text NOT NULL,
	"window_expires_at" timestamp with time zone,
	CONSTRAINT "effect_mq_dedupe_pkey" PRIMARY KEY("name","key")
);
--> statement-breakpoint
CREATE TABLE "effect_mq_flow_children" (
	"flow_id" text,
	"child_key" text,
	"name" text NOT NULL,
	"store_key" text NOT NULL,
	"spec" jsonb NOT NULL,
	"status" text NOT NULL,
	"exit" jsonb,
	"failed_reason" text,
	"cascaded" boolean NOT NULL,
	"pending_since" timestamp with time zone NOT NULL,
	CONSTRAINT "effect_mq_flow_children_pkey" PRIMARY KEY("flow_id","child_key")
);
--> statement-breakpoint
CREATE TABLE "effect_mq_flow_outbox" (
	"id" bigserial PRIMARY KEY,
	"flow_name" text NOT NULL,
	"parent_store_key" text NOT NULL,
	"report" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "effect_mq_job_attempts" (
	"job_id" text,
	"attempt" integer,
	"outcome" text NOT NULL,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone NOT NULL,
	"exit" jsonb,
	CONSTRAINT "effect_mq_job_attempts_pkey" PRIMARY KEY("job_id","attempt")
);
--> statement-breakpoint
CREATE TABLE "effect_mq_jobs" (
	"id" text PRIMARY KEY,
	"name" text NOT NULL,
	"queue" text NOT NULL,
	"state" text NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL,
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "effect_mq_jobs_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"payload" jsonb,
	"metadata" jsonb DEFAULT '{}' NOT NULL,
	"attempts_max" integer NOT NULL,
	"attempts_made" integer DEFAULT 0 NOT NULL,
	"stalled_count" integer DEFAULT 0 NOT NULL,
	"backoff" jsonb,
	"keep" jsonb,
	"timeout_ms" bigint,
	"cancel_requested" boolean DEFAULT false NOT NULL,
	"dedupe_key" text,
	"trace" jsonb,
	"parent" jsonb,
	"flow_fail_fast" boolean,
	"flow_pending" integer,
	"flow_completed" integer,
	"flow_failed" integer,
	"flow_cancelled" integer,
	"run_at" timestamp with time zone NOT NULL,
	"enqueued_at" timestamp with time zone NOT NULL,
	"processed_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"exit" jsonb,
	"failed_reason" text,
	"lock_token" text,
	"lock_expires_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "effect_mq_queue_control" (
	"queue" text PRIMARY KEY,
	"paused" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "effect_mq_schedules" (
	"key" text PRIMARY KEY,
	"job_name" text NOT NULL,
	"queue" text NOT NULL,
	"cron" text,
	"tz" text,
	"every_ms" bigint,
	"payload" jsonb,
	"metadata" jsonb DEFAULT '{}' NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL,
	"attempts_max" integer NOT NULL,
	"backoff" jsonb,
	"keep" jsonb,
	"timeout_ms" bigint,
	"group_name" text,
	"next_run_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "environment_variables" (
	"id" text PRIMARY KEY,
	"service_id" text NOT NULL,
	"name" text NOT NULL,
	"value" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "services" (
	"id" text PRIMARY KEY,
	"workspace_id" text NOT NULL,
	"type" text DEFAULT 'compose',
	"name" text,
	"slug" text,
	"icon" text,
	"value" text,
	"settings" jsonb DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "workspace" (
	"id" text PRIMARY KEY,
	"data_source_id" text NOT NULL,
	"organization_id" text NOT NULL,
	"name" text,
	"slug" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "account" (
	"id" text PRIMARY KEY,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "invitation" (
	"id" text PRIMARY KEY,
	"organization_id" text NOT NULL,
	"email" text NOT NULL,
	"role" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"inviter_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "member" (
	"id" text PRIMARY KEY,
	"organization_id" text NOT NULL,
	"user_id" text NOT NULL,
	"role" text DEFAULT 'member' NOT NULL,
	"created_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "organization" (
	"id" text PRIMARY KEY,
	"name" text NOT NULL,
	"slug" text NOT NULL UNIQUE,
	"logo" text,
	"created_at" timestamp NOT NULL,
	"metadata" text
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL UNIQUE,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	"active_organization_id" text,
	"impersonated_by" text
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY,
	"name" text NOT NULL,
	"email" text NOT NULL UNIQUE,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"role" text,
	"banned" boolean DEFAULT false,
	"ban_reason" text,
	"ban_expires" timestamp
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "data_source_organization_id_idx" ON "data_source" ("organization_id");--> statement-breakpoint
CREATE INDEX "deployment_logs_deployment_id_id_idx" ON "deployment_logs" ("deployment_id","id");--> statement-breakpoint
CREATE INDEX "deployments_service_id_created_at_idx" ON "deployments" ("service_id","created_at","id");--> statement-breakpoint
CREATE INDEX "effect_mq_flow_children_pending_idx" ON "effect_mq_flow_children" ("pending_since") WHERE "status" = 'pending';--> statement-breakpoint
CREATE INDEX "effect_mq_flow_children_cascade_idx" ON "effect_mq_flow_children" ("flow_id") WHERE "status" = 'cancelled' AND NOT "cascaded";--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_ready_idx" ON "effect_mq_jobs" ("queue","priority" DESC NULLS LAST,"seq") WHERE "state" = 'waiting';--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_delayed_idx" ON "effect_mq_jobs" ("queue","run_at") WHERE "state" = 'delayed';--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_active_idx" ON "effect_mq_jobs" ("lock_expires_at") WHERE "state" = 'active';--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_history_idx" ON "effect_mq_jobs" ("name","state","finished_at");--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_listing_idx" ON "effect_mq_jobs" ("enqueued_at" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_metadata_idx" ON "effect_mq_jobs" USING gin ("metadata" jsonb_path_ops);--> statement-breakpoint
CREATE INDEX "effect_mq_schedules_due_idx" ON "effect_mq_schedules" ("next_run_at");--> statement-breakpoint
CREATE INDEX "environment_variables_service_id_name_idx" ON "environment_variables" ("service_id","name");--> statement-breakpoint
CREATE INDEX "services_workspace_id_idx" ON "services" ("workspace_id");--> statement-breakpoint
CREATE UNIQUE INDEX "services_slug_idx" ON "services" ("slug");--> statement-breakpoint
CREATE INDEX "workspace_data_source_id_idx" ON "workspace" ("data_source_id","name");--> statement-breakpoint
CREATE INDEX "workspace_organization_id_idx" ON "workspace" ("organization_id");--> statement-breakpoint
CREATE UNIQUE INDEX "workspace_slug_idx" ON "workspace" ("slug");--> statement-breakpoint
CREATE INDEX "account_userId_idx" ON "account" ("user_id");--> statement-breakpoint
CREATE INDEX "invitation_organizationId_idx" ON "invitation" ("organization_id");--> statement-breakpoint
CREATE INDEX "invitation_email_idx" ON "invitation" ("email");--> statement-breakpoint
CREATE INDEX "member_organizationId_idx" ON "member" ("organization_id");--> statement-breakpoint
CREATE INDEX "member_userId_idx" ON "member" ("user_id");--> statement-breakpoint
CREATE INDEX "session_userId_idx" ON "session" ("user_id");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "verification" ("identifier");--> statement-breakpoint
ALTER TABLE "data_source" ADD CONSTRAINT "data_source_organization_id_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE RESTRICT;--> statement-breakpoint
ALTER TABLE "deployment_logs" ADD CONSTRAINT "deployment_logs_deployment_id_deployments_id_fkey" FOREIGN KEY ("deployment_id") REFERENCES "deployments"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "deployments" ADD CONSTRAINT "deployments_service_id_services_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "effect_mq_job_attempts" ADD CONSTRAINT "effect_mq_job_attempts_job_id_effect_mq_jobs_id_fkey" FOREIGN KEY ("job_id") REFERENCES "effect_mq_jobs"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "environment_variables" ADD CONSTRAINT "environment_variables_service_id_services_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT;--> statement-breakpoint
ALTER TABLE "services" ADD CONSTRAINT "services_workspace_id_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspace"("id") ON DELETE RESTRICT;--> statement-breakpoint
ALTER TABLE "workspace" ADD CONSTRAINT "workspace_data_source_id_data_source_id_fkey" FOREIGN KEY ("data_source_id") REFERENCES "data_source"("id") ON DELETE RESTRICT;--> statement-breakpoint
ALTER TABLE "workspace" ADD CONSTRAINT "workspace_organization_id_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE RESTRICT;--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "invitation" ADD CONSTRAINT "invitation_organization_id_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "invitation" ADD CONSTRAINT "invitation_inviter_id_user_id_fkey" FOREIGN KEY ("inviter_id") REFERENCES "user"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "member" ADD CONSTRAINT "member_organization_id_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "member" ADD CONSTRAINT "member_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE;